// GENERATED by scripts/market-fixture.mjs — do not edit by hand.
//
// The engine's own answers, so the two Swift ports that had to exist can be
// checked against them:
//
//   · MarketMath.swift — the tape, because RobinGhood is priced from the real
//     clock and the extension must price minutes the app never saw.
//   · NvFormat.swift   — the display rules, because a price computed here
//     arrives with no app-authored string attached to it.
//
// Regenerate with `npm run market:fixture` whenever lib/engine/market.ts or
// lib/engine/format.ts changes. A diff here that nobody asked for is the
// fixture reporting that the maths — or the way money is written — moved.
//
// 60 price samples · 6 tickers × 10 minutes
// 67 format samples

enum MarketFixture {
    struct Sample {
        let symbol: String
        let base: Double
        let drift: Double
        let vol: Double
        let minute: Int
        let price: Double
    }

    struct Format {
        /// "money" | "delta" | "percent" — the function in lib/engine/format.ts.
        let rule: String
        let input: Double
        let output: String
    }

    static let samples: [Sample] = [
        Sample(symbol: "NVSX", base: 148.2, drift: 0.09, vol: 0.9, minute: 0, price: 147.66694977651082),
        Sample(symbol: "NVSX", base: 148.2, drift: 0.09, vol: 0.9, minute: 29473920, price: 255.1379005265968),
        Sample(symbol: "NVSX", base: 148.2, drift: 0.09, vol: 0.9, minute: 29474311, price: 257.2766389992243),
        Sample(symbol: "NVSX", base: 148.2, drift: 0.09, vol: 0.9, minute: 29474707, price: 258.3366125268229),
        Sample(symbol: "NVSX", base: 148.2, drift: 0.09, vol: 0.9, minute: 29475359, price: 255.34426598513423),
        Sample(symbol: "NVSX", base: 148.2, drift: 0.09, vol: 0.9, minute: 29475900, price: 257.1699403747092),
        Sample(symbol: "NVSX", base: 148.2, drift: 0.09, vol: 0.9, minute: 29477340, price: 259.75468518460224),
        Sample(symbol: "NVSX", base: 148.2, drift: 0.09, vol: 0.9, minute: 30239505, price: 292.10211065176895),
        Sample(symbol: "NVSX", base: 148.2, drift: 0.09, vol: 0.9, minute: 34626492, price: 252.45540005062955),
        Sample(symbol: "NVSX", base: 148.2, drift: 0.09, vol: 0.9, minute: 35850960, price: 314.42539315504155),
        Sample(symbol: "BRWZ", base: 34.8, drift: 0.06, vol: 1.4, minute: 0, price: 35.51697824513902),
        Sample(symbol: "BRWZ", base: 34.8, drift: 0.06, vol: 1.4, minute: 29473920, price: 50.423565508723094),
        Sample(symbol: "BRWZ", base: 34.8, drift: 0.06, vol: 1.4, minute: 29474311, price: 49.96295926596834),
        Sample(symbol: "BRWZ", base: 34.8, drift: 0.06, vol: 1.4, minute: 29474707, price: 50.08793175789965),
        Sample(symbol: "BRWZ", base: 34.8, drift: 0.06, vol: 1.4, minute: 29475359, price: 50.67797252639177),
        Sample(symbol: "BRWZ", base: 34.8, drift: 0.06, vol: 1.4, minute: 29475900, price: 50.30443298909629),
        Sample(symbol: "BRWZ", base: 34.8, drift: 0.06, vol: 1.4, minute: 29477340, price: 49.14755125825954),
        Sample(symbol: "BRWZ", base: 34.8, drift: 0.06, vol: 1.4, minute: 30239505, price: 55.38011787893458),
        Sample(symbol: "BRWZ", base: 34.8, drift: 0.06, vol: 1.4, minute: 34626492, price: 50.024717047160514),
        Sample(symbol: "BRWZ", base: 34.8, drift: 0.06, vol: 1.4, minute: 35850960, price: 56.037365495883975),
        Sample(symbol: "GLRP", base: 76.5, drift: 0.04, vol: 1.1, minute: 0, price: 77.28827134872748),
        Sample(symbol: "GLRP", base: 76.5, drift: 0.04, vol: 1.1, minute: 29473920, price: 98.21523818156427),
        Sample(symbol: "GLRP", base: 76.5, drift: 0.04, vol: 1.1, minute: 29474311, price: 97.28471845484266),
        Sample(symbol: "GLRP", base: 76.5, drift: 0.04, vol: 1.1, minute: 29474707, price: 96.62786963977138),
        Sample(symbol: "GLRP", base: 76.5, drift: 0.04, vol: 1.1, minute: 29475359, price: 98.21236302292333),
        Sample(symbol: "GLRP", base: 76.5, drift: 0.04, vol: 1.1, minute: 29475900, price: 97.30783047600329),
        Sample(symbol: "GLRP", base: 76.5, drift: 0.04, vol: 1.1, minute: 29477340, price: 97.46404619439058),
        Sample(symbol: "GLRP", base: 76.5, drift: 0.04, vol: 1.1, minute: 30239505, price: 103.42618673183992),
        Sample(symbol: "GLRP", base: 76.5, drift: 0.04, vol: 1.1, minute: 34626492, price: 95.87994018258159),
        Sample(symbol: "GLRP", base: 76.5, drift: 0.04, vol: 1.1, minute: 35850960, price: 105.3183273259966),
        Sample(symbol: "PIXL", base: 212.4, drift: 0.18, vol: 2.2, minute: 0, price: 214.7767942008291),
        Sample(symbol: "PIXL", base: 212.4, drift: 0.18, vol: 2.2, minute: 29473920, price: 657.278169589041),
        Sample(symbol: "PIXL", base: 212.4, drift: 0.18, vol: 2.2, minute: 29474311, price: 650.475937420112),
        Sample(symbol: "PIXL", base: 212.4, drift: 0.18, vol: 2.2, minute: 29474707, price: 635.2297194930061),
        Sample(symbol: "PIXL", base: 212.4, drift: 0.18, vol: 2.2, minute: 29475359, price: 659.9330648293956),
        Sample(symbol: "PIXL", base: 212.4, drift: 0.18, vol: 2.2, minute: 29475900, price: 650.3893608319647),
        Sample(symbol: "PIXL", base: 212.4, drift: 0.18, vol: 2.2, minute: 29477340, price: 632.0317831675958),
        Sample(symbol: "PIXL", base: 212.4, drift: 0.18, vol: 2.2, minute: 30239505, price: 818.7434809285318),
        Sample(symbol: "PIXL", base: 212.4, drift: 0.18, vol: 2.2, minute: 34626492, price: 627.6273140887453),
        Sample(symbol: "PIXL", base: 212.4, drift: 0.18, vol: 2.2, minute: 35850960, price: 918.4888114342051),
        Sample(symbol: "MRCO", base: 58.9, drift: 0.11, vol: 1.8, minute: 0, price: 57.92813219596066),
        Sample(symbol: "MRCO", base: 58.9, drift: 0.11, vol: 1.8, minute: 29473920, price: 112.7556151123952),
        Sample(symbol: "MRCO", base: 58.9, drift: 0.11, vol: 1.8, minute: 29474311, price: 113.95359474744265),
        Sample(symbol: "MRCO", base: 58.9, drift: 0.11, vol: 1.8, minute: 29474707, price: 112.57578690826617),
        Sample(symbol: "MRCO", base: 58.9, drift: 0.11, vol: 1.8, minute: 29475359, price: 112.374558667765),
        Sample(symbol: "MRCO", base: 58.9, drift: 0.11, vol: 1.8, minute: 29475900, price: 115.75381443336207),
        Sample(symbol: "MRCO", base: 58.9, drift: 0.11, vol: 1.8, minute: 29477340, price: 113.89123271003058),
        Sample(symbol: "MRCO", base: 58.9, drift: 0.11, vol: 1.8, minute: 30239505, price: 133.50291251007027),
        Sample(symbol: "MRCO", base: 58.9, drift: 0.11, vol: 1.8, minute: 34626492, price: 113.91856036298306),
        Sample(symbol: "MRCO", base: 58.9, drift: 0.11, vol: 1.8, minute: 35850960, price: 145.63044296743809),
        Sample(symbol: "FINN", base: 6.42, drift: 0.2, vol: 5.5, minute: 0, price: 6.658568019809034),
        Sample(symbol: "FINN", base: 6.42, drift: 0.2, vol: 5.5, minute: 29473920, price: 22.929983463408192),
        Sample(symbol: "FINN", base: 6.42, drift: 0.2, vol: 5.5, minute: 29474311, price: 22.316945176631936),
        Sample(symbol: "FINN", base: 6.42, drift: 0.2, vol: 5.5, minute: 29474707, price: 20.976409485773587),
        Sample(symbol: "FINN", base: 6.42, drift: 0.2, vol: 5.5, minute: 29475359, price: 23.249518103724697),
        Sample(symbol: "FINN", base: 6.42, drift: 0.2, vol: 5.5, minute: 29475900, price: 22.863014429109327),
        Sample(symbol: "FINN", base: 6.42, drift: 0.2, vol: 5.5, minute: 29477340, price: 22.836390661949263),
        Sample(symbol: "FINN", base: 6.42, drift: 0.2, vol: 5.5, minute: 30239505, price: 27.624679380562327),
        Sample(symbol: "FINN", base: 6.42, drift: 0.2, vol: 5.5, minute: 34626492, price: 21.830913654161712),
        Sample(symbol: "FINN", base: 6.42, drift: 0.2, vol: 5.5, minute: 35850960, price: 33.17766621275154),
    ]

    static let formats: [Format] = [
        Format(rule: "money", input: 0.0, output: "$0"),
        Format(rule: "money", input: 1.0, output: "$1"),
        Format(rule: "money", input: 999.0, output: "$999"),
        Format(rule: "money", input: 1000.0, output: "$1,000"),
        Format(rule: "money", input: 9999.0, output: "$9,999"),
        Format(rule: "money", input: 9999.5, output: "$10,000"),
        Format(rule: "money", input: 10000.0, output: "$10K"),
        Format(rule: "money", input: 12400.0, output: "$12.4K"),
        Format(rule: "money", input: 99999.0, output: "$100K"),
        Format(rule: "money", input: 100000.0, output: "$100K"),
        Format(rule: "money", input: 999999.0, output: "$1000K"),
        Format(rule: "money", input: 1000000.0, output: "$1M"),
        Format(rule: "money", input: 1240000.0, output: "$1.2M"),
        Format(rule: "money", input: 3100000.0, output: "$3.1M"),
        Format(rule: "money", input: 999999999.0, output: "$1000M"),
        Format(rule: "money", input: 1000000000.0, output: "$1B"),
        Format(rule: "money", input: 1200000000.0, output: "$1.2B"),
        Format(rule: "money", input: 3250000.0, output: "$3.3M"),
        Format(rule: "money", input: 12250000.0, output: "$12.3M"),
        Format(rule: "money", input: 1050.0, output: "$1,050"),
        Format(rule: "money", input: 10500.0, output: "$10.5K"),
        Format(rule: "money", input: 105000.0, output: "$105K"),
        Format(rule: "money", input: -1.0, output: "−$1"),
        Format(rule: "money", input: -9999.0, output: "−$9,999"),
        Format(rule: "money", input: -12400.0, output: "−$12.4K"),
        Format(rule: "money", input: -3100000.0, output: "−$3.1M"),
        Format(rule: "money", input: -1200000000.0, output: "−$1.2B"),
        Format(rule: "delta", input: 0.0, output: "+$0"),
        Format(rule: "delta", input: 1.0, output: "+$1"),
        Format(rule: "delta", input: 999.0, output: "+$999"),
        Format(rule: "delta", input: 1000.0, output: "+$1,000"),
        Format(rule: "delta", input: 9999.0, output: "+$9,999"),
        Format(rule: "delta", input: 9999.5, output: "+$10,000"),
        Format(rule: "delta", input: 10000.0, output: "+$10K"),
        Format(rule: "delta", input: 12400.0, output: "+$12.4K"),
        Format(rule: "delta", input: 99999.0, output: "+$100K"),
        Format(rule: "delta", input: 100000.0, output: "+$100K"),
        Format(rule: "delta", input: 999999.0, output: "+$1000K"),
        Format(rule: "delta", input: 1000000.0, output: "+$1M"),
        Format(rule: "delta", input: 1240000.0, output: "+$1.2M"),
        Format(rule: "delta", input: 3100000.0, output: "+$3.1M"),
        Format(rule: "delta", input: 999999999.0, output: "+$1000M"),
        Format(rule: "delta", input: 1000000000.0, output: "+$1B"),
        Format(rule: "delta", input: 1200000000.0, output: "+$1.2B"),
        Format(rule: "delta", input: 3250000.0, output: "+$3.3M"),
        Format(rule: "delta", input: 12250000.0, output: "+$12.3M"),
        Format(rule: "delta", input: 1050.0, output: "+$1,050"),
        Format(rule: "delta", input: 10500.0, output: "+$10.5K"),
        Format(rule: "delta", input: 105000.0, output: "+$105K"),
        Format(rule: "delta", input: -1.0, output: "−$1"),
        Format(rule: "delta", input: -9999.0, output: "−$9,999"),
        Format(rule: "delta", input: -12400.0, output: "−$12.4K"),
        Format(rule: "delta", input: -3100000.0, output: "−$3.1M"),
        Format(rule: "delta", input: -1200000000.0, output: "−$1.2B"),
        Format(rule: "percent", input: 0.0, output: "+0%"),
        Format(rule: "percent", input: 0.04, output: "+0%"),
        Format(rule: "percent", input: 0.05, output: "+0.1%"),
        Format(rule: "percent", input: 1.0, output: "+1%"),
        Format(rule: "percent", input: 1.25, output: "+1.3%"),
        Format(rule: "percent", input: 2.4, output: "+2.4%"),
        Format(rule: "percent", input: 17.0, output: "+17%"),
        Format(rule: "percent", input: 17.05, output: "+17.1%"),
        Format(rule: "percent", input: 99.95, output: "+100%"),
        Format(rule: "percent", input: -0.04, output: "+0%"),
        Format(rule: "percent", input: -2.4, output: "−2.4%"),
        Format(rule: "percent", input: -17.5, output: "−17.5%"),
        Format(rule: "percent", input: -100.0, output: "−100%"),
    ]
}
