import "server-only";

import { createHash } from "node:crypto";

import eventsData from "@/data/events.json";

import { canonicalJson } from "./tape";

/**
 * Season pinning — why a board resets instead of being migrated.
 *
 * A tape is only meaningful against the engine that produced it. Change the
 * event library and the same seed draws different cards; change a KNOB and the
 * same decisions produce a different valuation. Old tapes then replay to
 * numbers their players never saw, and there is no honest way to re-verify
 * them: the run that happened is gone, and what is left is a run that would
 * happen now.
 *
 * So this is handled with seasons rather than heroics (docs/LEADERBOARD.md
 * §7.6). A season pins an engine version and an event-library hash; boards
 * reset when the season does; entries from a previous season stay exactly as
 * they were, read-only, rather than being re-verified into different numbers.
 *
 * `events_hash` is stored per run, not just per season, so the mismatch is
 * detectable at the row level: if a deploy changes `data/events.json` without
 * bumping the season, every run submitted afterwards carries a different hash
 * and the discrepancy shows up in one query instead of as a slow drift in the
 * top ten.
 */

export const ENGINE_VERSION = process.env.NOVUS_ENGINE_VERSION ?? "1";

export const SEASON = process.env.NOVUS_LEADERBOARD_SEASON ?? "2026-Q3";

/**
 * sha256 of the canonical event library.
 *
 * Canonical rather than raw bytes: `data/events.json` is generated by
 * `scripts/parse-events.mjs`, and a formatting change in the generator would
 * otherwise read as a content change and orphan every tape in the season.
 * Computed once at module load — it cannot change while the process is up,
 * because the import is part of the bundle.
 */
export const EVENTS_HASH = createHash("sha256")
  .update(canonicalJson(eventsData))
  .digest("hex");

export function sha256(text: string): string {
  return createHash("sha256").update(text).digest("hex");
}

/**
 * How a clean company name reaches the public board.
 *
 * `review` — the default, and what §9.3 asks for: every entry lands unlisted
 * and waits for a human. Nothing a child typed appears in public because a
 * regular expression approved of it.
 *
 * `clean` — an entry whose name passes every check in `moderation.ts` lists
 * immediately. Faster, and strictly worse: a blocklist catches what it knows
 * about. Opt in deliberately, per deployment, and only with the report route
 * and someone reading it.
 *
 * There is no third mode. "List everything" is not a setting, because a board
 * that publishes free text the instant it arrives is a liability a parent will
 * find before an engineer does.
 */
export type ListingPolicy = "review" | "clean";

export const LISTING_POLICY: ListingPolicy =
  process.env.NOVUS_BOARD_AUTOLIST === "clean" ? "clean" : "review";

/**
 * The shared secret that gates the moderation queue.
 *
 * Absent means the queue routes are off, not open. A moderation endpoint that
 * defaults to reachable is worse than no endpoint at all: it can unlist a
 * rival's entry and list an unreviewed one.
 */
export const MODERATOR_TOKEN = process.env.NOVUS_MODERATOR_TOKEN ?? "";

/** Ten submissions per profile per UTC day (§7.5). */
export const DAILY_SUBMISSION_LIMIT = 10;

/*
 * The board vocabulary lives in `./boards` because both sides need it and this
 * module is server-only. Re-exported so server code has one import to reach for.
 */
export { BOARDS, isBoard, type Board } from "./boards";
